menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/kosilence
    GitHub: https://github.com/kosilence
    Rss: /atom.xml

favicon: /favicon.ico
logo: /logo.png

# Comment
# e.g disqus: seansun
github:
  owner: kosilence
  repo: blog.cosin.tk
  oauth:
    client_id: a29417d1f351510ce909
    client_secret: 4a831dfc20286cdff8beb6cfe935583fa9c9b0ce
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-99915856-1

# Copyright Infomation
startyear: 2015
