menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/kosilence
    GitHub: https://github.com/kosilence
    Rss: /atom.xml

favicon: /favicon.ico
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
